### ISSUE TITLE
Could not pass event PlayerJoinEvent to ShopkeepersAddon v2.6

### ISSUE THREAD

**Issue by hoehoetvhss** [The-SpareParts/ShopkeepersNavAddon#4]
`[18:47:39 ERROR]: Could not pass event PlayerJoinEvent to ShopkeepersAddon v2.6
java.lang.NoSuchMethodError: 'com.nisovin.shopkeepers.shopkeeper.SKShopkeeperRegistry com.nisovin.shopkeepers.SKShopkeepersPlugin.getShopkeeperRegistry()'
        at dev.MrFlyn.shopkeeperNavAddon.GlobalShopGui.ShopkeeperSorter.updateSellingItemStacks(ShopkeeperSorter.java:34) ~[ShopkeepersAddon.jar:?]
        at dev.MrFlyn.shopkeeperNavAddon.GlobalShopGui.GuiListeners.onPlayerJoin(GuiListeners.java:30) ~[ShopkeepersAddon.jar:?]
        at com.destroystokyo.paper.event.executor.asm.generated.GeneratedEventExecutor411.execute(Unknown Source) ~[?:?]
        at org.bukkit.plugin.EventExecutor.lambda$create$1(EventExecutor.java:75) ~[paper-api-1.18.2-R0.1-SNAPSHOT.jar:?]
        at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:80) ~[paper-api-1.18.2-R0.1-SNAPSHOT.jar:git-Paper-246]
        at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:70) ~[paper-api-1.18.2-R0.1-SNAPSHOT.jar:?]
        at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:629) ~[paper-api-1.18.2-R0.1-SNAPSHOT.jar:?]
        at net.minecraft.server.players.PlayerList.postChunkLoadJoin(PlayerList.java:363) ~[paper-1.18.2.jar:git-Paper-246]
        at net.minecraft.server.players.PlayerList.lambda$placeNewPlayer$1(PlayerList.java:305) ~[paper-1.18.2.jar:git-Paper-246]
        at net.minecraft.server.network.ServerGamePacketListenerImpl.tick(ServerGamePacketListenerImpl.java:305) ~[?:?]
        at net.minecraft.network.Connection.tick(Connection.java:567) ~[?:?]
        at net.minecraft.server.network.ServerConnectionListener.tick(ServerConnectionListener.java:201) ~[?:?]
        at net.minecraft.server.MinecraftServer.tickChildren(MinecraftServer.java:1624) ~[paper-1.18.2.jar:git-Paper-246]
        at net.minecraft.server.dedicated.DedicatedServer.tickChildren(DedicatedServer.java:483) ~[paper-1.18.2.jar:git-Paper-246]
        at net.minecraft.server.MinecraftServer.tickServer(MinecraftServer.java:1458) ~[paper-1.18.2.jar:git-Paper-246]
        at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1227) ~[paper-1.18.2.jar:git-Paper-246]
        at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:317) ~[paper-1.18.2.jar:git-Paper-246]
        at java.lang.Thread.run(Thread.java:833) ~[?:?]`

**Comment by CloudeLecaw** [comment]
You should add this happens with New Shopkeeprts 1.25.1 and 1.18.2 server in combination - sugestion DOWNGRADE to Shopkeepers 2.14.0 for now (u need to use a backup u cant downgrade the database)

**Othher issues with the new Shopkeeper 2.15.1**

```
[22:24:40 ERROR]: [Minecraft] Could not pass event InventoryCloseEvent to ShopkeepersAddon v2.6
java.lang.IllegalStateException: API is not enabled!
        at com.nisovin.shopkeepers.api.internal.InternalShopkeepersAPI.getPlugin(InternalShopkeepersAPI.java:58) ~[Shopkeepers_2.14.0.jar:?]
        at com.nisovin.shopkeepers.api.ShopkeepersAPI.getPlugin(ShopkeepersAPI.java:54) ~[Shopkeepers_2.14.0.jar:?]
        at com.nisovin.shopkeepers.api.ShopkeepersAPI.getUIRegistry(ShopkeepersAPI.java:124) ~[Shopkeepers_2.14.0.jar:?]
        at dev.MrFlyn.shopkeeperNavAddon.Economy.EcoListeners.onInvClose(EcoListeners.java:205) ~[ShopkeepersAddon_2.6.2.jar:?]
        at com.destroystokyo.paper.event.executor.asm.generated.GeneratedEventExecutor747.execute(Unknown Source) ~[?:?]
        at org.bukkit.plugin.EventExecutor.lambda$create$1(EventExecutor.java:75) ~[paper-api-1.18.2-R0.1-SNAPSHOT.jar:?]
        at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:80) ~[paper-api-1.18.2-R0.1-SNAPSHOT.jar:git-Paper-274]
        at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:70) ~[paper-api-1.18.2-R0.1-SNAPSHOT.jar:?]
        at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:629) ~[paper-api-1.18.2-R0.1-SNAPSHOT.jar:?]
        at org.bukkit.craftbukkit.v1_18_R2.event.CraftEventFactory.handleInventoryCloseEvent(CraftEventFactory.java:1532) ~[paper-1.18.2.jar:git-Paper-274]
        at net.minecraft.server.network.ServerGamePacketListenerImpl.handleContainerClose(ServerGamePacketListenerImpl.java:2626) ~[?:?]
        at net.minecraft.server.network.ServerGamePacketListenerImpl.handleContainerClose(ServerGamePacketListenerImpl.java:2619) ~[?:?]
        at net.minecraft.network.protocol.game.ServerboundContainerClosePacket.handle(ServerboundContainerClosePacket.java:15) ~[?:?]
        at net.minecraft.network.protocol.game.ServerboundContainerClosePacket.handle(ServerboundContainerClosePacket.java:6) ~[?:?]
        at net.minecraft.network.protocol.PacketUtils.lambda$ensureRunningOnSameThread$1(PacketUtils.java:51) ~[?:?]
        at net.minecraft.server.TickTask.run(TickTask.java:18) ~[paper-1.18.2.jar:git-Paper-274]
        at net.minecraft.util.thread.BlockableEventLoop.doRunTask(BlockableEventLoop.java:153) ~[?:?]
        at net.minecraft.util.thread.ReentrantBlockableEventLoop.doRunTask(ReentrantBlockableEventLoop.java:23) ~[?:?]
        at net.minecraft.server.MinecraftServer.doRunTask(MinecraftServer.java:1399) ~[paper-1.18.2.jar:git-Paper-274]
        at net.minecraft.server.MinecraftServer.d(MinecraftServer.java:188) ~[paper-1.18.2.jar:git-Paper-274]
        at net.minecraft.util.thread.BlockableEventLoop.pollTask(BlockableEventLoop.java:126) ~[?:?]
        at net.minecraft.server.MinecraftServer.pollTaskInternal(MinecraftServer.java:1376) ~[paper-1.18.2.jar:git-Paper-274]
        at net.minecraft.server.MinecraftServer.pollTask(MinecraftServer.java:1369) ~[paper-1.18.2.jar:git-Paper-274]
        at net.minecraft.util.thread.BlockableEventLoop.runAllTasks(BlockableEventLoop.java:114) ~[?:?]
        at net.minecraft.server.MinecraftServer.tickServer(MinecraftServer.java:1503) ~[paper-1.18.2.jar:git-Paper-274]
        at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1225) ~[paper-1.18.2.jar:git-Paper-274]
        at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:315) ~[paper-1.18.2.jar:git-Paper-274]
        at java.lang.Thread.run(Thread.java:833) ~[?:?]
```

```
[22:55:47 ERROR]: [Minecraft] Could not pass event ShopkeeperEditedEvent to ShopkeepersAddon v2.6
java.lang.NoSuchMethodError: 'com.nisovin.shopkeepers.shopkeeper.SKShopkeeperRegistry com.nisovin.shopkeepers.SKShopkeepersPlugin.getShopkeeperRegistry()'
        at dev.MrFlyn.shopkeeperNavAddon.GlobalShopGui.ShopkeeperSorter.updateSellingItemStacks(ShopkeeperSorter.java:34) ~[ShopkeepersAddon_2.6.2.jar:?]
        at dev.MrFlyn.shopkeeperNavAddon.GlobalShopGui.GuiListeners.onShopkeeperEdit(GuiListeners.java:37) ~[ShopkeepersAddon_2.6.2.jar:?]
        at com.destroystokyo.paper.event.executor.asm.generated.GeneratedEventExecutor748.execute(Unknown Source) ~[?:?]
        at org.bukkit.plugin.EventExecutor.lambda$create$1(EventExecutor.java:75) ~[paper-api-1.18.2-R0.1-SNAPSHOT.jar:?]
        at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:80) ~[paper-api-1.18.2-R0.1-SNAPSHOT.jar:git-Paper-274]
        at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:70) ~[paper-api-1.18.2-R0.1-SNAPSHOT.jar:?]
        at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:629) ~[paper-api-1.18.2-R0.1-SNAPSHOT.jar:?]
        at com.nisovin.shopkeepers.ui.editor.EditorHandler.saveRecipes(EditorHandler.java:223) ~[Shopkeepers_2.15.1.jar:?]
        at com.nisovin.shopkeepers.ui.editor.AbstractEditorHandler.saveEditor(AbstractEditorHandler.java:946) ~[Shopkeepers_2.15.1.jar:?]
        at com.nisovin.shopkeepers.ui.editor.AbstractEditorHandler.onInventoryClose(AbstractEditorHandler.java:901) ~[Shopkeepers_2.15.1.jar:?]
        at com.nisovin.shopkeepers.ui.SKUIRegistry.onSessionEnded(SKUIRegistry.java:248) ~[Shopkeepers_2.15.1.jar:?]
        at com.nisovin.shopkeepers.ui.SKUIRegistry.endUISession(SKUIRegistry.java:235) ~[Shopkeepers_2.15.1.jar:?]
        at com.nisovin.shopkeepers.ui.SKUIRegistry.onInventoryClose(SKUIRegistry.java:220) ~[Shopkeepers_2.15.1.jar:?]
        at com.nisovin.shopkeepers.ui.UIListener.onInventoryClose(UIListener.java:263) ~[Shopkeepers_2.15.1.jar:?]
        at com.destroystokyo.paper.event.executor.MethodHandleEventExecutor.execute(MethodHandleEventExecutor.java:37) ~[paper-api-1.18.2-R0.1-SNAPSHOT.jar:?]
        at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:80) ~[paper-api-1.18.2-R0.1-SNAPSHOT.jar:git-Paper-274]
        at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:70) ~[paper-api-1.18.2-R0.1-SNAPSHOT.jar:?]
        at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:629) ~[paper-api-1.18.2-R0.1-SNAPSHOT.jar:?]
        at org.bukkit.craftbukkit.v1_18_R2.event.CraftEventFactory.handleInventoryCloseEvent(CraftEventFactory.java:1532) ~[paper-1.18.2.jar:git-Paper-274]
        at net.minecraft.server.network.ServerGamePacketListenerImpl.handleContainerClose(ServerGamePacketListenerImpl.java:2626) ~[?:?]
        at net.minecraft.server.network.ServerGamePacketListenerImpl.handleContainerClose(ServerGamePacketListenerImpl.java:2619) ~[?:?]
        at net.minecraft.network.protocol.game.ServerboundContainerClosePacket.handle(ServerboundContainerClosePacket.java:15) ~[?:?]
        at net.minecraft.network.protocol.game.ServerboundContainerClosePacket.handle(ServerboundContainerClosePacket.java:6) ~[?:?]
        at net.minecraft.network.protocol.PacketUtils.lambda$ensureRunningOnSameThread$1(PacketUtils.java:51) ~[?:?]
        at net.minecraft.server.TickTask.run(TickTask.java:18) ~[paper-1.18.2.jar:git-Paper-274]
        at net.minecraft.util.thread.BlockableEventLoop.doRunTask(BlockableEventLoop.java:153) ~[?:?]
        at net.minecraft.util.thread.ReentrantBlockableEventLoop.doRunTask(ReentrantBlockableEventLoop.java:23) ~[?:?]
        at net.minecraft.server.MinecraftServer.doRunTask(MinecraftServer.java:1399) ~[paper-1.18.2.jar:git-Paper-274]
        at net.minecraft.server.MinecraftServer.d(MinecraftServer.java:188) ~[paper-1.18.2.jar:git-Paper-274]
        at net.minecraft.util.thread.BlockableEventLoop.pollTask(BlockableEventLoop.java:126) ~[?:?]
        at net.minecraft.server.MinecraftServer.pollTaskInternal(MinecraftServer.java:1376) ~[paper-1.18.2.jar:git-Paper-274]
        at net.minecraft.server.MinecraftServer.pollTask(MinecraftServer.java:1369) ~[paper-1.18.2.jar:git-Paper-274]
        at net.minecraft.util.thread.BlockableEventLoop.runAllTasks(BlockableEventLoop.java:114) ~[?:?]
        at net.minecraft.server.MinecraftServer.tickServer(MinecraftServer.java:1503) ~[paper-1.18.2.jar:git-Paper-274]
        at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1225) ~[paper-1.18.2.jar:git-Paper-274]
        at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:315) ~[paper-1.18.2.jar:git-Paper-274]
        at java.lang.Thread.run(Thread.java:833) ~[?:?]
```

**Comment by CloudeLecaw** [comment]
tixed with the last version from discord update channel
